language: php

php:
  - 5.6
  - 7.0
  - hhvm

services:
  - redis-server

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_install:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-add travis.php.ini; fi

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

after_script:
  - bash -c '[[ -f "build/logs/clover.xml" ]] && wget https://scrutinizer-ci.com/ocular.phar'
  - bash -c '[[ -f "build/logs/clover.xml" ]] && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml'
